name: Migration Validation

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  validate-migrations:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: npm ci
      
    - name: Validate migration files (strict mode)
      run: npm run db:validate:strict
      
    - name: Run TypeScript type check
      run: npm run check
      
    # Optional: If you have a test database URL for integration testing
    # - name: Full migration validation with database
    #   env:
    #     DATABASE_URL: ${{ secrets.TEST_DATABASE_URL }}
    #   run: ./deploy.sh --dry-run --auto-confirm --skip-git-pull
      
    - name: Upload validation results
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: migration-validation-logs
        path: |
          deploy.log
          *.log
        retention-days: 7